### ISSUE TITLE
common instructions을 우선적으로 번역하고 검토하는 것을 제안합니다!

### ISSUE THREAD

**Issue by kohyounghwan** [42seoul-translation/subject_ko#16]
common instructions은 프로젝트마다 공통적으로 나오는 경우가 있는데요!

이 부분을 먼저 번역을 확정 짓는다면, 나올때마다 복붙할 수 있어서,

우선적으로 하는 것도 괜찮을 것같은데 어떻게 생각하세요!?

**Comment by wrfgt2e** [comment]
저도 common instruction부분은 항상 복붙해서 넣고 있는데, 나쁘지 않은 것같아요.
