### ISSUE TITLE
[Complete] Philosopher 번역

### ISSUE THREAD

**Issue by woolimi** [42seoul-translation/subject_ko#43]

**Comment by hochan222** [comment]
> 아 젠장.... 뻘짓으로 philiosopher 번역 풀리퀘를 날렸네요 -_-

@woolimi  앗앗 ㅋㅋㅋ 제가 다시 반영사항 넣어놓겠습니다

**Comment by hochan222** [comment]
제껀 다 반영했습니다. @woolimi 님꺼 반영해서 Merge 하면될 것 같습니다.
